# Site settings
title: Mümin Köykıran
description: Portfolyo Sayfası
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://muminkoykiran.com.tr" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mümin Köykıran
user_description: I am a Computer Scientist who likes and interests DevOps culture and Secure Systems Development Life Cycle (SDLC), Free and Open Source Softwares and Linux.
user_title: DevOps Engineer
email: muminkoykiran@gmail.com
twitter_username: MrKoykiran
github_username:  muminkoykiran
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules', 'vendor']

google_analytics:
  id: 'G-BPTZ4Z00PK'              # fill in your Google Analytics ID
